### ISSUE TITLE
Send array or object to json helper

### ISSUE THREAD

**Issue by ovsokolov** [bigcommerce/paper#123]
How we can send array or object of object availble in context

Need to do something like {{json [object1, obect2}}
or

{{json {'object1':object1, 'object2':object2} }}

**Comment by mcampa** [comment]
The json [helper](https://github.com/bigcommerce/paper/blob/master/helpers/json.js#L5) is just [JSON.stringify()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify) method call. 

I don't think you can construct objects like your example  in handlebars. For more info http://handlebarsjs.com/
